# Site settings
title: Roxie.dev
description: "밥잠코. 절절포!"
baseurl: ""
url: https://minjeung-kim.github.io
# Author
author:
  name: roxie
  url: https://minjeung-kim.github.io
  pic: /assets/img/zo.png
  about: "깊이 있는 개발자되기.<br/>
    성장 기록 & 개발 기록.<br/>"

# Contact links
email: focso5@gmail.com # Add your Email address
phone: # Add your Phone number
website: minjeung-kim.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: minjeung-kim # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Build settings
markdown: kramdown
highlighter: rouge
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post
  - jekyll-spaceship

# Permalinks
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

host: "0.0.0.0"
livereload: true
reload_port: 5678
